# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hryts/UCU/22/aks/acs_word_count1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hryts/UCU/22/aks/acs_word_count1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hryts/UCU/22/aks/acs_word_count1/CMakeFiles /home/hryts/UCU/22/aks/acs_word_count1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hryts/UCU/22/aks/acs_word_count1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lab4_word_count

# Build rule for target.
lab4_word_count: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lab4_word_count
.PHONY : lab4_word_count

# fast build rule for target.
lab4_word_count/fast:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/build
.PHONY : lab4_word_count/fast

count_words.o: count_words.cpp.o

.PHONY : count_words.o

# target to build an object file
count_words.cpp.o:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/count_words.cpp.o
.PHONY : count_words.cpp.o

count_words.i: count_words.cpp.i

.PHONY : count_words.i

# target to preprocess a source file
count_words.cpp.i:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/count_words.cpp.i
.PHONY : count_words.cpp.i

count_words.s: count_words.cpp.s

.PHONY : count_words.s

# target to generate assembly for a file
count_words.cpp.s:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/count_words.cpp.s
.PHONY : count_words.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/main.cpp.s
.PHONY : main.cpp.s

merge.o: merge.cpp.o

.PHONY : merge.o

# target to build an object file
merge.cpp.o:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/merge.cpp.o
.PHONY : merge.cpp.o

merge.i: merge.cpp.i

.PHONY : merge.i

# target to preprocess a source file
merge.cpp.i:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/merge.cpp.i
.PHONY : merge.cpp.i

merge.s: merge.cpp.s

.PHONY : merge.s

# target to generate assembly for a file
merge.cpp.s:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/merge.cpp.s
.PHONY : merge.cpp.s

read_config.o: read_config.cpp.o

.PHONY : read_config.o

# target to build an object file
read_config.cpp.o:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/read_config.cpp.o
.PHONY : read_config.cpp.o

read_config.i: read_config.cpp.i

.PHONY : read_config.i

# target to preprocess a source file
read_config.cpp.i:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/read_config.cpp.i
.PHONY : read_config.cpp.i

read_config.s: read_config.cpp.s

.PHONY : read_config.s

# target to generate assembly for a file
read_config.cpp.s:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/read_config.cpp.s
.PHONY : read_config.cpp.s

read_file.o: read_file.cpp.o

.PHONY : read_file.o

# target to build an object file
read_file.cpp.o:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/read_file.cpp.o
.PHONY : read_file.cpp.o

read_file.i: read_file.cpp.i

.PHONY : read_file.i

# target to preprocess a source file
read_file.cpp.i:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/read_file.cpp.i
.PHONY : read_file.cpp.i

read_file.s: read_file.cpp.s

.PHONY : read_file.s

# target to generate assembly for a file
read_file.cpp.s:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/read_file.cpp.s
.PHONY : read_file.cpp.s

unpack.o: unpack.cpp.o

.PHONY : unpack.o

# target to build an object file
unpack.cpp.o:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/unpack.cpp.o
.PHONY : unpack.cpp.o

unpack.i: unpack.cpp.i

.PHONY : unpack.i

# target to preprocess a source file
unpack.cpp.i:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/unpack.cpp.i
.PHONY : unpack.cpp.i

unpack.s: unpack.cpp.s

.PHONY : unpack.s

# target to generate assembly for a file
unpack.cpp.s:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/unpack.cpp.s
.PHONY : unpack.cpp.s

write_result.o: write_result.cpp.o

.PHONY : write_result.o

# target to build an object file
write_result.cpp.o:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/write_result.cpp.o
.PHONY : write_result.cpp.o

write_result.i: write_result.cpp.i

.PHONY : write_result.i

# target to preprocess a source file
write_result.cpp.i:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/write_result.cpp.i
.PHONY : write_result.cpp.i

write_result.s: write_result.cpp.s

.PHONY : write_result.s

# target to generate assembly for a file
write_result.cpp.s:
	$(MAKE) -f CMakeFiles/lab4_word_count.dir/build.make CMakeFiles/lab4_word_count.dir/write_result.cpp.s
.PHONY : write_result.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... lab4_word_count"
	@echo "... edit_cache"
	@echo "... count_words.o"
	@echo "... count_words.i"
	@echo "... count_words.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... merge.o"
	@echo "... merge.i"
	@echo "... merge.s"
	@echo "... read_config.o"
	@echo "... read_config.i"
	@echo "... read_config.s"
	@echo "... read_file.o"
	@echo "... read_file.i"
	@echo "... read_file.s"
	@echo "... unpack.o"
	@echo "... unpack.i"
	@echo "... unpack.s"
	@echo "... write_result.o"
	@echo "... write_result.i"
	@echo "... write_result.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

